---
# This is an example configuration file for the AdWords API client library.
# Please fill in the required fields, and copy it over to your home directory.
:authentication:
  # Authentication method, for web applications OAuth is recommended.
  :method: OAuth2

  # Auth parameters for OAuth2.0 method.
  # Set the OAuth2 client id and secret. Register your application here to
  # obtain these values:
  #   https://console.developers.google.com/
  :oauth2_client_id: "92151906708-m34ak7nogsnsndgub3176rhe88jckas4.apps.googleusercontent.com"
  :oauth2_client_secret: "FiXuGzR-OPZOJYaElNh40Iec"
  # Optional, see: https://developers.google.com/accounts/docs/OAuth2WebServer
  # :oauth2_state: INSERT_OAUTH2_STATE_HERE
  # :oauth2_access_type: INSERT_OAUTH2_ACCESS_TYPE_HERE
  # :oauth2_approval_prompt: INSERT_OAUTH2_APPROVAL_PROMPT_HERE
  # Callback is set up by the application at runtime.
  :oauth2_callback: "http://grupoemporium.com/"
  :oauth2_token: 
    # :refresh_token: ""
    :access_token: "ya29.ZgJHQE6OiSXpLV_mIDnvQIAvz-2iidVSzviE4d5Or59TqjAgRE5knUBTutNftqKx06PBPA"
  #:oauth2_refresh_token: "1/dnvnwMiUgUt2Z8szeWkjEQ9RzDiP-W0rlhCIV3WhkXxIgOrJDtdun6zK6XiATCKT"

  # Other parameters.
  :developer_token: "vRY3gyXNWkxUYaZHQnQsgQ"
  # If you access only one account you can specify it here.
  :client_customer_id: "455-349-0136"
  #:user_agent: sumosuggest
:service:
  # Only production environment is available now, see: http://goo.gl/Plu3o
  :environment: PRODUCTION
:connection:
  # Enable to request all responses to be compressed.
  :enable_gzip: false
  # If your proxy connection requires authentication, make sure to include it in
  # the URL, e.g.: http://user:password@proxy_hostname:8080
  # :proxy: INSERT_PROXY_HERE
:library:
  :log_level: INFO


# {
#   "authorization_uri"=>"https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=92151906708-m34ak7nogsnsndgub3176rhe88jckas4.apps.googleusercontent.com&redirect_uri=http://grupoemporium.com/&response_type=code&scope=https://www.googleapis.com/auth/drive.metadata.readonly", 
#   "token_credential_uri"=>"https://accounts.google.com/o/oauth2/token", 
#   "client_id"=>"92151906708-m34ak7nogsnsndgub3176rhe88jckas4.apps.googleusercontent.com", 
#   "client_secret"=>nil, 
#   "scope"=>["https://www.googleapis.com/auth/drive.metadata.readonly"], 
#   "state"=>nil, 
#   "code"=>nil, 
#   "redirect_uri"=>"http://grupoemporium.com/", 
#   "username"=>nil, 
#   "password"=>nil, 
#   "issuer"=>nil, 
#   "audience"=>nil, 
#   "person"=>nil, 
#   "expiry"=>60, 
#   "signing_key"=>nil, 
#   "refresh_token"=>"1/6EFKsrQsf-UBFUhzCrAl1-WsDqG9TWeeCSkflh-gnbZIgOrJDtdun6zK6XiATCKT", 
#   "access_token"=>"ya29.XQL87ketBhnWqfRLYy7TVMQznIDiXmLvDwVI9JuXWnrXRwXg76lRzwRL2KtWFyP2H06i", 
#   "id_token"=>nil, 
#   "extension_parameters"=>{}
# }