---
# This is an example configuration file for the AdWords API client library.
# Please fill in the required fields, and copy it over to your home directory.
:authentication:
  # Authentication method, for web applications OAuth is recommended.
  :method: OAuth2

  # Auth parameters for OAuth2.0 method.
  # Set the OAuth2 client id and secret. Register your application here to
  # obtain these values:
  #   https://console.developers.google.com/
  :oauth2_client_id: "747644059389-0gde6651jgtt1alnsv1tljvtrekqi5ck.apps.googleusercontent.com"
  :oauth2_client_secret: 0ECMgo6yhnw8HPZK_rGDiyp8
  # Optional, see: https://developers.google.com/accounts/docs/OAuth2WebServer
  #:oauth2_state: INSERT_OAUTH2_STATE_HERE
  #:oauth2_access_type: INSERT_OAUTH2_ACCESS_TYPE_HERE
  #:oauth2_approval_prompt: INSERT_OAUTH2_APPROVAL_PROMPT_HERE
  # Callback is set up by the application at runtime.
  :oauth2_callback: "http://grupoemporium.com/"
  :oauth2_token: 
    :refresh_token: "1/fwEq6LPMHZ0gx0aKqgAsaouf_szj5RrCcyJV5v0mDApIgOrJDtdun6zK6XiATCKT"
    :access_token: "ya29.TwKS5-eyR2M-eaTqgypwK-iypnVZBaKzTVVtvBUuiNDlzexVLXlbLMae9raa_xxGWYMw"
  #:oauth2_refresh_token: "1/dnvnwMiUgUt2Z8szeWkjEQ9RzDiP-W0rlhCIV3WhkXxIgOrJDtdun6zK6XiATCKT"

  # Other parameters.
  :developer_token: "qYl9CSMSjoaw45gL2-JYbw"
  # If you access only one account you can specify it here.
  :client_customer_id: "676-937-4228"
  #:user_agent: sumosuggest
:service:
  # Only production environment is available now, see: http://goo.gl/Plu3o
  :environment: PRODUCTION
:connection:
  # Enable to request all responses to be compressed.
  :enable_gzip: false
  # If your proxy connection requires authentication, make sure to include it in
  # the URL, e.g.: http://user:password@proxy_hostname:8080
  # :proxy: INSERT_PROXY_HERE
:library:
  :log_level: INFO
